version: "2"

services:
    app:
        build: ./docker/app
        depends_on:
            - db
        volumes:
            - .:/var/www
            - /var/www/var/cache
            - /var/www/var/sessions

    db:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: enmarche
            MYSQL_DATABASE: enmarche
            MYSQL_USER: enmarche
            MYSQL_PASSWORD: enmarche

    mailcatcher:
        image: schickling/mailcatcher

    tools:
        build: ./docker/tools
        depends_on:
            - db
        volumes_from:
            - app

    pma:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        environment:
            PMA_HOST: db
            PMA_USER: enmarche
            PMA_PASSWORD: enmarche
